Pd 359 update
visualcamp/seeso-sample-windows pull request #2
Opened 2021-04-26 07:36 UTC by aurian89

- 2.4.0 API 에 맞도록 수정

2021-04-26 07:37 UTC, aurian89 commented on callback.cc
> +void Callback::OnAttention(uint64_t timestamp, float score) {
OnAttention, Blink, Drowsiness 로 OnStatus 콜백을 분리하여 반환

2021-04-26 07:37 UTC, aurian89 commented on main.cpp
> +  auto userStatusOption = seeso::UserStatusOption();;
UserStatusOption 클래스를 생성하여 option 정보 반환하도록 수정

2021-04-26 07:38 UTC, aurian89 commented on seeso/include/seeso/callback_interface.h
> +  virtual void OnAttention(uint64_t timestamp, float score) = 0;
OnStatus 인터페이스를 OnAttention, Blink, Drowsiness 로 분할

2021-04-26 07:39 UTC, aurian89 commented on seeso/include/seeso/core_callback.h
> +class CoreCallback : private internal::CallbackDispatcher<CoreCallback> {
mobile_Tracker와 직접적인 콜백을 core callback으로 분리

2021-04-26 07:40 UTC, aurian89 commented on seeso/include/seeso/eye_tracker.h
> +  int initialize(const std::string& license_key, UserStatusOption &userStatusOption);
UserStatusOption 클래스를 파라미터로 받도록 수정

2021-04-26 07:40 UTC, aurian89 commented on seeso/include/seeso/user_status_option.h
> +class UserStatusOption {
StatusOption 클래스 추가

2021-04-26 07:42 UTC, aurian89 commented on seeso/include/seeso/eye_tracker.cc
> +  }
Tier 정보 잘못된 경우 ERROR_NOT_ADVANCED_TIER (15) + 2 반환됨 [추후 wrapper 쪽에서 반환하도록 수정 예정]

2021-04-26 08:36 UTC, lackhole requested changes

2021-04-26 08:36 UTC, lackhole commented on seeso/include/seeso/user_status_option.h
> +   explicit UserStatusOption();
여기서 기본 생성자는 불필하니 지우시는게 좋을 것 같습니다

2021-04-26 08:36 UTC, lackhole commented on seeso/include/seeso/user_status_option.h
> +   bool getUseBlink();
const 한정자 추가해주세요~

2021-04-26 08:36 UTC, lackhole commented on seeso/include/seeso/eye_tracker.h
> +  int initialize(const std::string& license_key, UserStatusOption &userStatusOption);
const reference로 받는게 좋아 보입니다~

2021-04-26 08:36 UTC, lackhole commented on seeso/include/seeso/user_status_option.cc
> +UserStatusOption::UserStatusOption() {
헤더에서 멤버 초기화 해서 굳이 안해도 될 것 같아

2021-04-26 08:36 UTC, lackhole commented on seeso/include/seeso/core_callback.cc
> +      bool isBlinkLeft = false;
`bool isBlinkLeft = blinkL > 0.f;`로 한줄로 처리하는게 가독성이 좋아 보입니다

2021-04-26 08:36 UTC, lackhole commented on seeso/include/seeso/core_callback.h
> +  explicit CoreCallback();
생성자 지우는게 좋을 것 같습니당

2021-04-27 01:36 UTC, lackhole approved these changes

2021-04-27 01:37 UTC, merged